apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: registry
        k8s-app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: registry
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Registry
  name: registry
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - nodePort: 32050
    port: 80
    targetPort: 5000
  selector:
    k8s-app: registry