apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: registry
        k8s-app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: "/var/lib/registry"
          name: docker-registry
      volumes:
      - name: docker-registry
        persistentVolumeClaim:
          claimName: pvc-docker-registry
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: registry
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Registry
  name: registry
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - nodePort: 32050
    port: 80
    targetPort: 5000
  selector:
    k8s-app: registry
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-docker-registry
  namespace: kube-system
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/k8s/docker-registry
    server: llano
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-docker-registry
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi