#apiVersion: batch/v1beta1
#kind: CronJob
#metadata:
#  name: nestwatch
#  namespace: monitoring
#  labels:
#    app: nestwatch
#spec:
#  successfulJobsHistoryLimit: 2
#  failedJobsHistoryLimit: 3
#  schedule: "*/1 * * * *"
#  jobTemplate:
#    spec:
#      template:
#        spec:
#          restartPolicy: OnFailure
#          containers:
#          - name: nestwatch
#            image: registry.kube-system/nestwatch:0.1
#            volumeMounts:
#            - mountPath: "/app/nestwatch.conf"
#              name: nestwatch-conf
#              readOnly: true
#          volumes:
#          - name: nestwatch-conf
#            secret:
#              secretName: secret-nestwatch
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nestwatch-build
  namespace: monitoring
  labels:
    app: nestwatch-build
spec:
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: init
            image: alpine/git
            args:
            - "clone"
            - "https://github.com/chrbayer84/kubernetes-montgomery.git"
            - "/git/source"
            volumeMounts:
            - name: source
              mountPath: /git
          containers:
          - name: kaniko
            image: gcr.io/kaniko-project/executor
            args: ["--dockerfile=/workspace/source/nestwatch/Dockerfile",
                   "--context=/workspace/source/nestwatch",
                   " --destination=registry.kube-system/nestwatch:0.1"]
            volumeMounts:
            - name: source
              mountPath: /workspace/
            - name: docker
              mountPath: /kaniko/secrets
              readOnly: true
            env:
            - name: DOCKER_CONFIG
              value: /kaniko/secrets
          restartPolicy: OnFailure
          volumes:
          - name: source
            emptyDir: {}
          - name: docker
            configMap:
              name: docker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker
  namespace: monitoring
data:
  docker.json: |-
    {}
