apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nestwatch
  namespace: monitoring
  labels:
    app: nestwatch
spec:
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          #  restartPolicy: OnFailure
          restartPolicy: Never
          containers:
          - name: nestwatch
            image: llano:32050/nestwatch:latest
            command:
            - /app/nestwatch
            args: ["-c", "/app/conf/nestwatch.conf"]
            volumeMounts:
            - mountPath: "/app/conf"
              name: nestwatch-conf
              readOnly: true
          volumes:
          - name: nestwatch-conf
            secret:
              secretName: secret-nestwatch
---
apiVersion: v1
kind: Pod
metadata:
  name: nestwatch-build
  namespace: monitoring
  labels:
    app: nestwatch-build
spec:
  initContainers:
  - name: init
    image: alpine/git
    args:
    - "clone"
    - "https://github.com/chrbayer84/kubernetes-montgomery.git"
    - "/git/source"
    volumeMounts:
    - name: source
      mountPath: /git
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor
    args: ["--dockerfile=/workspace/source/nestwatch/Dockerfile",
           "--context=/workspace/source/nestwatch",
           "--destination=registry.kube-system/nestwatch:latest",
           "--insecure"
          ]
    volumeMounts:
    - name: source
      mountPath: /workspace/
    - name: docker
      mountPath: /kaniko/secrets
      readOnly: true
    env:
    - name: DOCKER_CONFIG
      value: /kaniko/secrets
#  restartPolicy: OnFailure
  restartPolicy: Never
  volumes:
  - name: source
    emptyDir: {}
  - name: docker
    configMap:
      name: docker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker
  namespace: monitoring
data:
  config.json: |-
    {
            "auths": {
            }
    }
#    {
#            "auths": {
#                    "http:/registry.kube-system/": {
#                            "auth": "XXXXXXXXXXXXX",
#                            "email": "x.y@gmail.com"
#                    }
#            }
#    }
