apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestwatch
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: nestwatch
  replicas: 1
  template:
    metadata:
      labels:
        app: nestwatch
    spec:
      containers:
      - name: nestwatch
        image: llano:32050/nestwatch:latest
        volumeMounts:
        - mountPath: "/app/conf"
          name: nestwatch-conf
          readOnly: true
      volumes:
      - name: nestwatch-conf
        secret:
          secretName: secret-nestwatch
---
apiVersion: v1
kind: Pod
metadata:
  name: nestwatch-build
  namespace: monitoring
  labels:
    app: nestwatch-build
spec:
  initContainers:
  - name: init
    image: alpine/git
    args:
    - "clone"
    - "https://github.com/chrbayer84/kubernetes-montgomery.git"
    - "/git/source"
    volumeMounts:
    - name: source
      mountPath: /git
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug-v0.6.0
    args: ["--dockerfile=/workspace/source/nestwatch/Dockerfile",
           "--context=/workspace/source/nestwatch",
           "--destination=registry.kube-system/nestwatch:latest",
           "--insecure"
          ]
    volumeMounts:
    - name: source
      mountPath: /workspace/
    - name: docker
      mountPath: /kaniko/secrets
      readOnly: true
    env:
    - name: DOCKER_CONFIG
      value: /kaniko/secrets
#  restartPolicy: OnFailure
  restartPolicy: Never
  volumes:
  - name: source
    emptyDir: {}
  - name: docker
    configMap:
      name: docker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker
  namespace: monitoring
data:
  config.json: |-
    {
            "auths": {
            }
    }
