apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wordpress
  namespace: wordpress
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/k8s/wordpress
    server: llano
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wordpress
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi